// src/components/Technologies/Technologies.tsx
import TechnologiesInterface from "../../interfaces/technologies.interface";
import style from "./index.module.css";

const Technologies = ({ title, text }: TechnologiesInterface) => {
  return (
    <div className={style.container}>
      <h2 className={style.title}>{title}</h2>
      <div className={style.images_container}>
        <img
          className={style.image}
          src="https://juststickers.in/wp-content/uploads/2019/07/nodejs.png"
          alt="nodejs_logo"
        />
        <img
          className={style.image}
          src="https://keenethics.com/wp-content/uploads/2021/10/Express.js.svg"
          alt="express_logo"
        />
        <img
          className={style.image}
          src="https://upload.wikimedia.org/wikipedia/commons/0/00/HTML5_logo_black.svg"
          alt="html5_logo"
        />
        <img
          className={style.image}
          id={style.css_logo}
          src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/CSS3_logo_and_wordmark.svg/1452px-CSS3_logo_and_wordmark.svg.png"
          alt="css3_logo"
        />
        <img
          id={style.js_logo}
          className={style.image}
          src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/JavaScript-logo.png/768px-JavaScript-logo.png"
          alt="js_logo"
        />
        <img
          className={style.image}
          src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Typescript_logo_2020.svg/2048px-Typescript_logo_2020.svg.png"
          alt="ts_logo"
        />
        <img
          className={style.image}
          src="https://res.cloudinary.com/deotitxt8/image/upload/v1733404612/portfolio/r0vxhlnzhb4zxaovmpsm.png"
          alt="github_logo"
        />
        <img
          className={style.image}
          src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Git_icon.svg/2048px-Git_icon.svg.png"
          alt="git_logo"
        />
        <img
          className={style.image}
          src="https://cdn.iconscout.com/icon/free/png-256/free-mongodb-logo-icon-download-in-svg-png-gif-file-formats--wordmark-programming-langugae-freebies-pack-logos-icons-1175140.png?f=webp"
          alt="mongodb_logo"
        />
        <img
          id={style.mongoose_logo}
          className={style.image}
          src="https://img1.daumcdn.net/thumb/R800x0/?scode=mtistory2&fname=https%3A%2F%2Ft1.daumcdn.net%2Fcfile%2Ftistory%2F99177233598415E22A"
          alt="mongoose_logo"
        />
        <img
          className={style.image}
          src="https://cdn.icon-icons.com/icons2/2415/PNG/512/postgresql_original_wordmark_logo_icon_146392.png"
          alt="postgresql_logo"
        />
        <img
          className={style.image}
          src="https://cdn.icon-icons.com/icons2/2415/PNG/512/sequelize_original_logo_icon_146348.png"
          alt="sequelize_logo"
        />
        <img
          className={style.image}
          src="https://ies.solutions/wordpress/wp-content/uploads/jwt.png"
          alt="jwt_logo"
        />
        <img
          className={style.image}
          src="https://cdn.iconscout.com/icon/free/png-256/free-react-logo-icon-download-in-svg-png-gif-file-formats--wordmark-programming-langugae-freebies-pack-logos-icons-1175110.png?f=webp&w=256"
          alt="react_logo"
        />
        <img
          id={style.tailwind_logo}
          className={style.image}
          src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Tailwind_CSS_Logo.svg/512px-Tailwind_CSS_Logo.svg.png"
          alt="tailwind_logo"
        />
      </div>

      <div className={style.github_container}>
        <img
          className={style.github_stats}
          src="https://github-readme-stats.vercel.app/api/top-langs?username=calvinuhh&show_icons=true&locale=en&layout=compact"
          alt="github_stats"
        />
        <p className={style.github_text}>{text}</p>
      </div>
    </div>
  );
};

export default Technologies;

// components/Technologies.vue
<template>
  <div class="flex w-[1200px] flex-col mx-auto gap-[10px] my-[100px]">
    <h2 class="text-white text-[24px] font-noto font-bold mb-[30px]">Tecnologías</h2>

    <div class="flex flex-wrap gap-[20px] justify-center w-[800px] mx-auto mb-[100px]">
      <img
        v-for="(tech, index) in techLogos"
        :key="index"
        :src="tech.src"
        :alt="tech.alt"
        :class="tech.class"
      />
    </div>

    <div class="flex justify-center flex-col gap-[10px] mx-auto">
      <img
        class="w-[300px]"
        src="https://github-readme-stats.vercel.app/api/top-langs?username=calvinuhh&show_icons=true&locale=en&layout=compact"
        alt="github_stats"
      />
      <p class="text-white font-noto">Tomado de las estadísticas de GitHub</p>
    </div>
  </div>
</template>

<script setup>
const techLogos = [

  {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Typescript_logo_2020.svg/2048px-Typescript_logo_2020.svg.png",
    alt: "ts_logo",
    class: "w-[100px] h-[100px] transition-all duration-[0.2s] ease-out hover:scale-[1.3]"
  },
  {
    src: "https://juststickers.in/wp-content/uploads/2019/07/nodejs.png",
    alt: "nodejs_logo",
    class: "w-[100px] h-[100px] transition-all duration-[0.2s] ease-out hover:scale-[1.3]"
  },
  {
    src: "https://keenethics.com/wp-content/uploads/2021/10/Express.js.svg",
    alt: "express_logo",
    class: "w-[100px] h-[100px] transition-all duration-[0.2s] ease-out hover:scale-[1.3]"
  },
  {
    src: "https://res.cloudinary.com/deotitxt8/image/upload/v1733404612/portfolio/r0vxhlnzhb4zxaovmpsm.png",
    alt: "github_logo",
    class: "w-[100px] h-[100px] transition-all duration-[0.2s] ease-out hover:scale-[1.3]"
  },
  {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Git_icon.svg/2048px-Git_icon.svg.png",
    alt: "git_logo",
    class: "w-[100px] h-[100px] transition-all duration-[0.2s] ease-out hover:scale-[1.3]"
  },
  {
    src: "https://cdn.iconscout.com/icon/free/png-256/free-mongodb-logo-icon-download-in-svg-png-gif-file-formats--wordmark-programming-langugae-freebies-pack-logos-icons-1175140.png?f=webp",
    alt: "mongodb_logo",
    class: "w-[100px] h-[100px] transition-all duration-[0.2s] ease-out hover:scale-[1.3]"
  },
  {
    src: "https://img1.daumcdn.net/thumb/R800x0/?scode=mtistory2&fname=https%3A%2F%2Ft1.daumcdn.net%2Fcfile%2Ftistory%2F99177233598415E22A",
    alt: "mongoose_logo",
    class: "w-[150px] h-[100px] transition-all duration-[0.2s] ease-out hover:scale-[1.3]"
  },
  {
    src: "https://1000marcas.net/wp-content/uploads/2020/11/MySQL-logo.png",
    alt: "mysql_logo",
    class: "w-[120px] h-[100px] transition-all duration-[0.2s] ease-out hover:scale-[1.3]"
  },
  {
    src: "https://res.cloudinary.com/deotitxt8/image/upload/v1738689627/portfolio/vuo6yvkonmr9hlmdmwvy.png",
    alt: "postgresql_logo",
    class: "w-[100px] h-[100px] transition-all duration-[0.2s] ease-out hover:scale-[1.3]"
  },
  {
    src: "https://res.cloudinary.com/deotitxt8/image/upload/v1738689779/portfolio/pwdivzo10lo32nezzygw.png",
    alt: "sequelize_logo",
    class: "w-[130px] h-[100px] transition-all duration-[0.2s] ease-out hover:scale-[1.3]"
  },
  {
    src: "https://res.cloudinary.com/deotitxt8/image/upload/v1733404612/portfolio/so51nrmeyaxtwby5cewo.png",
    alt: "jwt_logo",
    class: "w-[180px] h-[100px] transition-all duration-[0.2s] ease-out hover:scale-[1.3]"
  },
  {
    src: "https://cdn.iconscout.com/icon/free/png-256/free-react-logo-icon-download-in-svg-png-gif-file-formats--wordmark-programming-langugae-freebies-pack-logos-icons-1175110.png?f=webp&w=256",
    alt: "react_logo",
    class: "w-[100px] h-[100px] transition-all duration-[0.2s] ease-out hover:scale-[1.3]"
  },
  {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Tailwind_CSS_Logo.svg/512px-Tailwind_CSS_Logo.svg.png",
    alt: "tailwind_logo",
    class: "w-[150px] h-[100px] transition-all duration-[0.2s] ease-out hover:scale-[1.3]"
  },
  {
    src: "https://nuxt.com/assets/design-kit/icon-green.svg",
    alt: "nuxt_logo",
    class: "w-[150px] h-[100px] transition-all duration-[0.2s] ease-out hover:scale-[1.3]"
  },
  {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/N8n-logo-new.svg/2560px-N8n-logo-new.svg.png",
    alt: "nuxt_logo",
    class: "w-[180px] h-[100px] transition-all duration-[0.2s] ease-out hover:scale-[1.3]"
  }
]
</script>
